version: "3.7"

services:
  db:
    image: postgres:15.1-alpine
    container_name: db_container
    restart: always
    env_file:
      - .env-prod
  db_test:
    container_name: db_test
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env-prod
    ports:
      - "5433:5432"