version: "3.7"

services:
  db_test:
    image: postgres:15.1-alpine
    container_name: db_test_container
    env_file:
      - .env-example

  app_test:
    build:
      context: .
    env_file:
      - .env-example
    container_name: fastapi_app_tests
    command: [ "/fastapi_app/docker/app_test.sh" ]
    ports:
      - "8001:8001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/health" ]
      interval: 10s
      timeout: 10s
      retries: 3
    depends_on:
      - db_test
      - redis
    links:
      - redis:redis
  redis:
    image: redis:6
    container_name: redis
    restart: unless-stopped
    expose:
      - 6379