version: "3.7"

services:
  db_test:
    image: postgres:15.1-alpine
    container_name: db_test_container
    env_file:
      - .env-example

  app_test:
    build:
      context: .
    env_file:
      - .env-example
    stdin_open: true
    tty: true
    container_name: fastapi_app_tests
    depends_on:
      - db_test
      - redis
    links:
      - redis:redis
  redis:
    image: redis:6
    container_name: redis_tests
    restart: unless-stopped
    expose:
      - 6380
