version: "3.7"

services:
  db:
    image: postgres:15.1-alpine
    container_name: db_container
    env_file:
      - .env-prod
  db_test:
    image: postgres:15.1-alpine
    container_name: db_test_container
    env_file:
      - .env-prod
  app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db